#!/usr/bin/env python3
"""
Societal value hint generator that rebuilds the takeable-only hover hint files from the EU5 game files.

Scrapes government reforms, laws (policies), estate privileges, advances, societal value axes, ages,
and script value constants from the live game install, then regenerates the four mod files that
replace the C++ GetLeftHint/GetRightHint blob with per-axis hint lists filtered at render time:

  - in_game/gui/glorpUI_generated_societal_value_hints.gui           (tooltip template redefinitions)
  - in_game/common/script_values/glorpui_generated_societal_value_hint_script_values.txt
  - in_game/common/customizable_localization/glorpui_generated_societal_value_hint_loc.txt
  - main_menu/localization/english/glorpui_generated_societal_value_hints_l_english.yml

A candidate is anything with a monthly_towards_<side> country modifier. Takeability evaluates live
through the hand-written chokepoint triggers in glorpui_societal_value_hint_scripted_triggers.txt;
advance-unlocked reforms and laws additionally get a baked "reachable" clause (advance researched,
or its age reached and its branch's gateway institution embraced).
Run after updating to a new EU5 version.

The game directory is auto-detected from the known Steam install locations. Set
'game_directory' (or 'beta_game_directory') in tools/config.toml to override, or
pass --game-dir.

Usage:
    python tools/glorpui_societal_value_hints_updater.py                 # standard EU5 install
    python tools/glorpui_societal_value_hints_updater.py -b              # closed beta install
    python tools/glorpui_societal_value_hints_updater.py --game-dir DIR  # explicit game directory
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
CONFIG_PATH = SCRIPT_DIR / "config.toml"

STEAM_GAME_PATHS = [
    Path(r"C:\Steam\steamapps\common\Europa Universalis V\game"),
    Path(r"C:\Program Files (x86)\Steam\steamapps\common\Europa Universalis V\game"),
    Path(r"C:\Program Files\Steam\steamapps\common\Europa Universalis V\game"),
]

BETA_STEAM_GAME_PATHS = [
    Path(r"C:\Steam\steamapps\common\Project Caesar Review\game"),
    Path(r"C:\Program Files (x86)\Steam\steamapps\common\Project Caesar Review\game"),
    Path(r"C:\Program Files\Steam\steamapps\common\Project Caesar Review\game"),
]

UTF8_BOM = b"\xef\xbb\xbf"

GUI_OUTPUT = PROJECT_ROOT / "in_game" / "gui" / "glorpUI_generated_societal_value_hints.gui"
SCRIPT_VALUES_OUTPUT = (
    PROJECT_ROOT
    / "in_game"
    / "common"
    / "script_values"
    / "glorpui_generated_societal_value_hint_script_values.txt"
)
CUSTOM_LOC_OUTPUT = (
    PROJECT_ROOT
    / "in_game"
    / "common"
    / "customizable_localization"
    / "glorpui_generated_societal_value_hint_loc.txt"
)
LOC_OUTPUT = (
    PROJECT_ROOT
    / "main_menu"
    / "localization"
    / "english"
    / "glorpui_generated_societal_value_hints_l_english.yml"
)

# Country variable set by the "Show Unavailable Suggestions for Pushing Societal Values" setting.
VANILLA_HINT_VARIABLE = "showUnavailableSocietalValueSuggestions"

# Behavior switches, each a one-line flip.
DISPATCH_MODE = "scope_equality"  # scope_equality | string_equals
COLOR_WRAP = "green"  # green | plain
NEWLINE_MODE = "trailing"  # trailing | leading
REACH_MODE = "reachable_age"  # reachable_age | startable_now

HEADER = (
    "# Auto-generated by tools/glorpui_societal_value_hints_updater.py - takeable-only societal value "
    "hint {what} from the EU5 game government_reforms, laws, estate_privileges, and advances files."
)

# Law fields that are depth-2 blocks but not policies; a monthly_towards push inside one is law-owned.
LAW_FIELD_BLOCKS = {
    "potential",
    "allow",
    "locked",
    "custom_tags",
    "country_modifier",
    "province_modifier",
    "location_modifier",
    "on_activate",
    "on_deactivate",
    "on_pay_price",
    "estate_preferences",
    "ai_will_do",
    "law_religion_group",
}

BLOCK_RE = re.compile(r"^([\w.\-]+)\s*=\s*\{")
PUSH_RE = re.compile(r"^monthly_towards_(\w+)\s*=\s*([\w.\-]+)")
SCALAR_RE = re.compile(r"^([\w.\-]+)\s*=\s*([\w.\-]+)\s*$")
LOC_KEY_RE = re.compile(r"^\s*([\w.\-']+):\d*\s*\"")
INSTITUTION_RE = re.compile(r"has_embraced_institution\s*=\s*institution:(\w+)")

KIND_ORDER = {"pv": 0, "r": 1, "p": 2}
# Names are wrapped in the engine's #TOOLTIP:<TYPE>,<key> structs (tooltip_structs_l_english.yml)
# so each suggestion hovers with its own object tooltip, like the C++ hint's GetName output.
KIND_LINE_FORMAT = {
    "pv": "@hint! Grant #TOOLTIP:ESTATE_PRIVILEGE,{key} #L ${key}$#!#!: {val}",
    "r": "@hint! Add the #TOOLTIP:GOVERNMENT_REFORM,{key} #L ${key}$#!#! [government_reform|e]: {val}",
    "p": "@hint! Enact the #TOOLTIP:POLICY,{key} #L ${key}$#!#! [policy]: {val}",
}


def parse_braces(line):
    """Return (net_depth_change, has_open) for a line, ignoring strings and comments."""
    in_string = False
    depth = 0
    has_open = False
    for ch in line:
        if ch == "#" and not in_string:
            break
        if ch == '"':
            in_string = not in_string
        if not in_string:
            if ch == "{":
                depth += 1
                has_open = True
            elif ch == "}":
                depth -= 1
    return depth, has_open


def find_block_end(lines, start):
    """Find the end of a brace-delimited block starting at `start`. Returns end index (exclusive)."""
    brace_depth = 0
    seen_open = False
    i = start
    while i < len(lines):
        delta, has_open = parse_braces(lines[i])
        brace_depth += delta
        if has_open:
            seen_open = True
        i += 1
        if seen_open and brace_depth <= 0:
            break
    return i


def iter_top_level_blocks(lines):
    """Yield (key, start, end) for every top-level block in a file's lines."""
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        if not stripped or stripped.startswith("#"):
            i += 1
            continue
        match = BLOCK_RE.match(stripped)
        if match:
            end = find_block_end(lines, i)
            yield match.group(1), i, end
            i = end
            continue
        if "{" in stripped:
            i = find_block_end(lines, i)
        else:
            i += 1


def read_lines(path):
    return path.read_text(encoding="utf-8-sig").split("\n")


def content_files(directory):
    """Sorted .txt files of a game content directory, minus readme/info files."""
    return [
        p
        for p in sorted(directory.glob("*.txt"))
        if not p.stem.lower().startswith(("readme", "_"))
    ]


def block_pushes(lines, start, end, errors, where):
    """Return [(side_token, raw_value)] for every monthly_towards line inside the block."""
    pushes = []
    for i in range(start + 1, end):
        match = PUSH_RE.match(lines[i].strip())
        if match:
            pushes.append((match.group(1), match.group(2)))
    return pushes


def block_has_depth1_key(lines, start, end, key):
    """True if the block has a direct child (scalar or block) named `key`."""
    depth = 0
    for i in range(start, end):
        stripped = lines[i].strip()
        if depth == 1 and re.match(rf"^{key}\s*=", stripped):
            return True
        delta, _ = parse_braces(lines[i])
        depth += delta
    return False


def depth1_values(lines, start, end, key):
    """All values of direct scalar children named `key` inside the block."""
    values = []
    depth = 0
    for i in range(start, end):
        stripped = lines[i].strip()
        if depth == 1:
            match = re.match(rf"^{key}\s*=\s*([\w.\-]+)", stripped)
            if match:
                values.append(match.group(1))
        delta, _ = parse_braces(lines[i])
        depth += delta
    return values


def depth1_block_keys(lines, start, end, name):
    """Bare tokens inside a direct child block named `name`, or []."""
    depth = 0
    i = start
    while i < end:
        stripped = lines[i].strip()
        if depth == 1 and re.match(rf"^{name}\s*=\s*\{{", stripped):
            sub_end = find_block_end(lines, i)
            keys = []
            for j in range(i, sub_end):
                cleaned = lines[j].split("#")[0].replace("{", " ").replace("}", " ")
                for token in cleaned.split():
                    if token not in (name, "=") and re.fullmatch(r"\w+", token):
                        keys.append(token)
            return keys
        delta, _ = parse_braces(lines[i])
        depth += delta
        i += 1
    return []


def depth1_block_text(lines, start, end, name):
    """Flattened inner text of a direct child block named `name`, or ''."""
    depth = 0
    i = start
    while i < end:
        stripped = lines[i].strip()
        if depth == 1 and re.match(rf"^{name}\s*=\s*\{{", stripped):
            sub_end = find_block_end(lines, i)
            parts = []
            for j in range(i, sub_end):
                text = lines[j].split("#")[0].strip()
                if j == i:
                    text = re.sub(rf"^{name}\s*=\s*\{{", "", text).strip()
                if text:
                    parts.append(text)
            body = " ".join(parts)
            closing = body.rfind("}")
            if closing != -1:
                body = (body[:closing] + body[closing + 1 :]).strip()
            return body
        delta, _ = parse_braces(lines[i])
        depth += delta
        i += 1
    return ""


def iter_depth2_blocks(lines, start, end):
    """Yield (key, start, end) for every depth-2 block inside a top-level block."""
    depth = 0
    i = start
    while i < end:
        stripped = lines[i].strip()
        if depth == 1:
            match = BLOCK_RE.match(stripped)
            if match:
                sub_end = find_block_end(lines, i)
                yield match.group(1), i, sub_end
                for j in range(i, sub_end):
                    delta, _ = parse_braces(lines[j])
                    depth += delta
                i = sub_end
                continue
        delta, _ = parse_braces(lines[i])
        depth += delta
        i += 1


def collect_ages(game_root, errors):
    age_dir = game_root / "in_game" / "common" / "age"
    ages = []
    for path in content_files(age_dir):
        for key, _, _ in iter_top_level_blocks(read_lines(path)):
            ages.append(key)
    if not ages:
        errors.append(f"no age definitions found under {age_dir}")
    return ages


def collect_axes(game_root, errors):
    sv_dir = game_root / "in_game" / "common" / "societal_values"
    axes = []
    side_map = {}
    for path in content_files(sv_dir):
        for key, _, _ in iter_top_level_blocks(read_lines(path)):
            parts = key.split("_vs_")
            if len(parts) != 2:
                errors.append(f"societal value key not of the form X_vs_Y: {key}")
                continue
            axes.append((key, parts[0], parts[1]))
            for token, side in ((parts[0], "left"), (parts[1], "right")):
                if token in side_map:
                    errors.append(f"duplicate societal value side token: {token}")
                side_map[token] = (key, side)
    return axes, side_map


def collect_constants(game_root):
    path = game_root / "main_menu" / "common" / "script_values" / "default_values.txt"
    constants = {}
    for line in read_lines(path):
        match = SCALAR_RE.match(line.strip())
        if match:
            try:
                constants[match.group(1)] = float(match.group(2))
            except ValueError:
                pass
    return constants


def resolve_value(raw, constants, errors, where):
    try:
        return float(raw)
    except ValueError:
        pass
    if raw in constants:
        return constants[raw]
    errors.append(f"unresolvable push value '{raw}' at {where}")
    return None


def collect_simple_candidates(directory, kind, constants, errors, warnings, ages):
    """Reforms and privileges: [(kind, key, None, token, value)], {key} with a locked field, and
    per-key structural availability clauses (engine fields is_implementable_in does not check:
    reform government/age, privilege estate)."""
    candidates = []
    locked_keys = set()
    structural = {}
    for path in content_files(directory):
        lines = read_lines(path)
        for key, start, end in iter_top_level_blocks(lines):
            if block_has_depth1_key(lines, start, end, "locked"):
                locked_keys.add(key)
            clauses = []
            if kind == "r":
                for government in depth1_values(lines, start, end, "government"):
                    clauses.append(f"government_type = government_type:{government}")
                for age in depth1_values(lines, start, end, "age"):
                    if age not in ages:
                        errors.append(f"reform {key} names unknown age {age}")
                    elif ages.index(age) > 0:
                        clauses.append(f"current_age_or_later = {{ age = {age} }}")
            else:
                for estate in depth1_values(lines, start, end, "estate"):
                    clauses.append(f"country_has_estate = estate_type:{estate}")
            if clauses:
                structural[key] = clauses
            for token, raw in block_pushes(lines, start, end, errors, key):
                value = resolve_value(raw, constants, errors, f"{path.name}:{key}")
                if value is None:
                    continue
                if value <= 0:
                    warnings.append(f"skipping non-positive push {key} monthly_towards_{token} = {raw}")
                    continue
                candidates.append((kind, key, None, token, value))
    return candidates, locked_keys, structural


def collect_policy_candidates(laws_dir, constants, errors, warnings):
    """Policies: [(kind, key, law, token, value)], {law} with a locked field, and per-law structural
    availability clauses (engine fields is_implementable_in does not check: law_gov_group,
    law_religion_group, law_country_group)."""
    candidates = []
    locked_laws = set()
    law_structural = {}
    seen_policies = {}
    io_laws_skipped = 0
    for path in content_files(laws_dir):
        lines = read_lines(path)
        for law_key, law_start, law_end in iter_top_level_blocks(lines):
            # IO-type laws are voted through their international organization, so their policies
            # are never directly enactable by a country.
            if "international_organization" in depth1_values(lines, law_start, law_end, "type"):
                io_laws_skipped += 1
                continue
            if block_has_depth1_key(lines, law_start, law_end, "locked"):
                locked_laws.add(law_key)
            clauses = []
            for government in depth1_values(lines, law_start, law_end, "law_gov_group"):
                clauses.append(f"government_type = government_type:{government}")
            for tag in depth1_values(lines, law_start, law_end, "law_country_group"):
                clauses.append(f"has_or_had_tag = {tag}")
            religions = depth1_block_keys(lines, law_start, law_end, "law_religion_group")
            if len(religions) == 1:
                clauses.append(f"religion ?= religion:{religions[0]}")
            elif religions:
                clauses.append(
                    "OR = { " + " ".join(f"religion ?= religion:{r}" for r in religions) + " }"
                )
            if clauses:
                law_structural[law_key] = clauses
            for sub_key, sub_start, sub_end in iter_depth2_blocks(lines, law_start, law_end):
                pushes = block_pushes(lines, sub_start, sub_end, errors, sub_key)
                if sub_key in LAW_FIELD_BLOCKS:
                    if pushes:
                        warnings.append(
                            f"skipping law-owned push(es) in {path.name}:{law_key}.{sub_key}"
                        )
                    continue
                if not pushes:
                    continue
                if sub_key in seen_policies and seen_policies[sub_key] != law_key:
                    errors.append(
                        f"policy key {sub_key} appears under two laws: "
                        f"{seen_policies[sub_key]} and {law_key}"
                    )
                seen_policies[sub_key] = law_key
                for token, raw in pushes:
                    value = resolve_value(raw, constants, errors, f"{path.name}:{law_key}.{sub_key}")
                    if value is None:
                        continue
                    if value <= 0:
                        warnings.append(
                            f"skipping non-positive push {sub_key} monthly_towards_{token} = {raw}"
                        )
                        continue
                    candidates.append(("p", sub_key, law_key, token, value))
    if io_laws_skipped:
        print(f"Skipped {io_laws_skipped} international-organization laws (policies not country-enactable)")
    return candidates, locked_laws, law_structural


def collect_advances(game_root, errors):
    """advance -> {age, parents, institutions, governments, potential}, plus reform -> [advance],
    law -> [advance], policy -> [advance] unlock maps."""
    adv_dir = game_root / "in_game" / "common" / "advances"
    advances = {}
    reform_unlocks = {}
    law_unlocks = {}
    policy_unlocks = {}
    for path in content_files(adv_dir):
        lines = read_lines(path)
        for key, start, end in iter_top_level_blocks(lines):
            ages = depth1_values(lines, start, end, "age")
            parents = depth1_values(lines, start, end, "requires") + depth1_values(
                lines, start, end, "in_tree_of"
            )
            institutions = set()
            for i in range(start, end):
                for match in INSTITUTION_RE.finditer(lines[i]):
                    institutions.add(match.group(1))
            if not ages:
                errors.append(f"advance without an age field: {path.name}:{key}")
                continue
            advances[key] = {
                "age": ages[0],
                "parents": parents,
                "institutions": institutions,
                "governments": depth1_values(lines, start, end, "government"),
                "potential": depth1_block_text(lines, start, end, "potential"),
            }
            for reform in depth1_values(lines, start, end, "unlock_government_reform"):
                reform_unlocks.setdefault(reform, []).append(key)
            for law in depth1_values(lines, start, end, "unlock_law"):
                law_unlocks.setdefault(law, []).append(key)
            for policy in depth1_values(lines, start, end, "unlock_policy"):
                policy_unlocks.setdefault(policy, []).append(key)
    return advances, reform_unlocks, law_unlocks, policy_unlocks


def chain_institutions(advance, advances, cache, visiting=None):
    """Gateway institutions of an advance's whole requires/in_tree_of chain, including its own."""
    if advance in cache:
        return cache[advance]
    if visiting is None:
        visiting = set()
    if advance in visiting or advance not in advances:
        return set()
    visiting.add(advance)
    result = set(advances[advance]["institutions"])
    for parent in advances[advance]["parents"]:
        result |= chain_institutions(parent, advances, cache, visiting)
    visiting.discard(advance)
    cache[advance] = result
    return result


def collect_loc_keys(game_root):
    keys = set()
    for path in game_root.rglob("*_l_english.yml"):
        try:
            text = path.read_text(encoding="utf-8-sig")
        except (OSError, UnicodeDecodeError):
            continue
        for line in text.split("\n"):
            match = LOC_KEY_RE.match(line)
            if match:
                keys.add(match.group(1))
    return keys


def reach_clauses(advance_key, advances, ages, inst_cache, errors):
    """Per-advance reach alternatives for the OR list, or None when reach is unconditional.
    is_locked_for does not reflect advance unlocks (verified in-game), so the researched state
    is covered by has_advance."""
    if REACH_MODE == "startable_now":
        return [f"has_advance_available = {advance_key}"]
    info = advances[advance_key]
    if info["age"] not in ages:
        errors.append(f"advance {advance_key} names unknown age {info['age']}")
        return [f"has_advance = {advance_key}"]
    conditions = []
    if ages.index(info["age"]) > 0:
        conditions.append(f"current_age_or_later = {{ age = {info['age']} }}")
    for institution in sorted(chain_institutions(advance_key, advances, inst_cache)):
        conditions.append(f"has_embraced_institution = institution:{institution}")
    for government in info["governments"]:
        conditions.append(f"government_type = government_type:{government}")
    if info["potential"]:
        conditions.append(info["potential"])
    if not conditions:
        return None
    alternatives = [f"has_advance = {advance_key}"]
    if len(conditions) == 1:
        alternatives.append(conditions[0])
    else:
        alternatives.append("AND = { " + " ".join(conditions) + " }")
    return alternatives


class Candidate:
    def __init__(self, kind, key, law, token, value, reach_map, structural):
        self.kind = kind
        self.key = key
        self.law = law
        self.token = token
        self.value = value
        # "law" / "self" -> advance list (reach relaxation) or None (strict engine-lock line).
        self.reach_map = reach_map
        self.structural = list(structural)

    def core_call(self):
        if self.kind == "r":
            return f"glorpui_svh_reform_core = {{ KEY = {self.key} }}"
        return f"glorpui_svh_policy_core = {{ KEY = {self.key} LAW = {self.law} }}"

    def _reach_or(self, advance_list, advances, ages, inst_cache, errors):
        alternatives = []
        for advance_key in advance_list:
            per_advance = reach_clauses(advance_key, advances, ages, inst_cache, errors)
            if per_advance is None:
                return []
            alternatives.extend(per_advance)
        return ["OR = {", *[f"\t{a}" for a in alternatives], "}"]

    def trigger_lines(self, advances, ages, inst_cache, errors):
        """Trigger statements (implicit AND) expressing current takeability. Each unlock dimension
        (the owning law's advances, the reform's or policy's own) independently emits a reach OR
        or, without a reach relaxation, its engine-lock line."""
        lines = list(self.structural)
        if self.kind == "pv":
            return lines + [f"glorpui_svh_privilege_takeable = {{ KEY = {self.key} }}"]
        lines.append(self.core_call())
        if self.kind == "p":
            law_reach = self.reach_map.get("law")
            if law_reach:
                lines += self._reach_or(law_reach, advances, ages, inst_cache, errors)
            else:
                lines.append(f"law:{self.law} = {{ NOT = {{ is_locked_for = PREV }} }}")
        self_reach = self.reach_map.get("self")
        if self_reach:
            lines += self._reach_or(self_reach, advances, ages, inst_cache, errors)
        elif self.kind == "r":
            lines.append(f"government_reform:{self.key} = {{ NOT = {{ is_locked_for = PREV }} }}")
        else:
            lines.append(f"policy:{self.key} = {{ NOT = {{ is_locked_for = PREV }} }}")
        return lines

    def entry_name(self):
        return f"glorpui_svh_{self.token}_{self.kind}_{self.key}"

    def line_key(self):
        return f"GLORP_UI_SVH_{self.token.upper()}_{self.kind.upper()}_{self.key.upper()}"

    def line_value(self):
        if COLOR_WRAP == "green":
            val = f"#color_green +{self.value:.2f}#!"
        else:
            val = f"+{self.value:.2f}"
        text = KIND_LINE_FORMAT[self.kind].format(key=self.key, val=val)
        return f"\\n{text}" if NEWLINE_MODE == "leading" else f"{text}\\n"


def sort_side(candidates):
    return sorted(candidates, key=lambda c: (KIND_ORDER[c.kind], -c.value, c.key))


def visible_expression(token, side):
    script_value = (
        "GuiScope.AddScope('glorpui_country', Player.MakeScope)"
        f".ScriptValue('glorpui_svh_visible_{token}')"
    )
    if DISPATCH_MODE == "scope_equality":
        script_value = (
            "GuiScope.AddScope('glorpui_sv', SocietalValue.MakeScope)"
            ".AddScope('glorpui_country', Player.MakeScope)"
            f".ScriptValue('glorpui_svh_visible_{token}')"
        )
        return f"[GreaterThan_CFixedPoint({script_value}, '(CFixedPoint)0')]"
    label = "GetLeftLabelWithNoTooltip" if side == "left" else "GetRightLabelWithNoTooltip"
    return (
        f"[And(StringEquals(SocietalValue.{label}, Localize('{token}_focus')), "
        f"GreaterThan_CFixedPoint({script_value}, '(CFixedPoint)0'))]"
    )


def build_gui(sides_by_axis):
    def side_blocks(side, title_key):
        blocks = []
        for token in sides_by_axis[side]:
            blocks.append(
                "\n".join(
                    [
                        "\t\tTooltipScrolledStringPairList = {",
                        f'\t\t\tvisible = "{visible_expression(token, side)}"',
                        '\t\t\tblockoverride "block_scrollarea" {',
                        "\t\t\t\tmaximumsize = { -1 160 }",
                        "\t\t\t}",
                        "",
                        '\t\t\tblockoverride "block_title" {',
                        f'\t\t\t\ttext = "{title_key}"',
                        '\t\t\t\tdefault_format = "#help"',
                        "\t\t\t}",
                        "",
                        f"\t\t\ttextcontext = \"[Localize('GLORP_UI_SVH_BODY_{token.upper()}')]\"",
                        "\t\t}",
                    ]
                )
            )
        return "\n\n".join(blocks)

    def vanilla_block(title_key, fn):
        return "\n".join(
            [
                "\t\tTooltipScrolledStringPairList = {",
                f"\t\t\tvisible = \"[Player.MakeScope.GetVariable('{VANILLA_HINT_VARIABLE}').IsSet]\"",
                '\t\t\tblockoverride "block_scrollarea" {',
                "\t\t\t\tmaximumsize = { -1 160 }",
                "\t\t\t}",
                "",
                '\t\t\tblockoverride "block_title" {',
                f'\t\t\t\ttext = "{title_key}"',
                '\t\t\t\tdefault_format = "#help"',
                "\t\t\t}",
                "",
                f'\t\t\ttextcontext = "[SocietalValue.{fn}(Player.Self)]"',
                "\t\t}",
            ]
        )

    marker = "\t\t# GlorpUI: C++ {fn} blob kept behind a setting, per-axis lists filtered to takeable suggestions otherwise."
    parts = [
        HEADER.format(what="tooltip templates"),
        "",
        "template SocietalValueCountryLeft_tooltip {",
        "\tusing = SocietalValueLeft_tooltip",
        '\tblockoverride "societal_value_left_tooltip_extra" {',
        marker.format(fn="GetLeftHint"),
        vanilla_block("TO_MOVE_FURTHER_TO_LEFT", "GetLeftHint"),
        "",
        side_blocks("left", "TO_MOVE_FURTHER_TO_LEFT"),
        "\t}",
        "}",
        "",
        "template SocietalValueCountryRight_tooltip {",
        "\tusing = SocietalValueRight_tooltip",
        '\tblockoverride "societal_value_right_tooltip_extra" {',
        marker.format(fn="GetRightHint"),
        vanilla_block("TO_MOVE_FURTHER_TO_RIGHT", "GetRightHint"),
        "",
        side_blocks("right", "TO_MOVE_FURTHER_TO_RIGHT"),
        "\t}",
        "}",
        "",
    ]
    return "\n".join(parts)


def build_script_values(sides_by_axis, by_token, token_axis, advances, ages, inst_cache, errors):
    blocks = []
    for side in ("left", "right"):
        for token in sides_by_axis[side]:
            axis = token_axis[token]
            lines = [
                f"glorpui_svh_visible_{token} = {{",
                "\tvalue = 0",
                "\tif = {",
                "\t\tlimit = {",
            ]
            if DISPATCH_MODE == "scope_equality":
                lines.append(f"\t\t\tscope:glorpui_sv = societal_value_type:{axis}")
            lines += [
                "\t\t\tscope:glorpui_country = {",
                f"\t\t\t\thas_societal_value = societal_value_type:{axis}",
                f"\t\t\t\tNOT = {{ has_variable = {VANILLA_HINT_VARIABLE} }}",
                "\t\t\t\tOR = {",
            ]
            for candidate in sort_side(by_token[token]):
                statements = candidate.trigger_lines(advances, ages, inst_cache, errors)
                if len(statements) == 1:
                    lines.append(f"\t\t\t\t\t{statements[0]}")
                else:
                    lines.append("\t\t\t\t\tAND = {")
                    lines += [f"\t\t\t\t\t\t{s}" for s in statements]
                    lines.append("\t\t\t\t\t}")
            lines += [
                "\t\t\t\t}",
                "\t\t\t}",
                "\t\t}",
                "\t\tvalue = 1",
                "\t}",
                "}",
            ]
            blocks.append("\n".join(lines))
    return HEADER.format(what="visibility script values") + "\n\n" + "\n\n".join(blocks) + "\n"


def build_custom_loc(sides_by_axis, by_token, advances, ages, inst_cache, errors):
    entries = []
    for side in ("left", "right"):
        for token in sides_by_axis[side]:
            for candidate in sort_side(by_token[token]):
                statements = candidate.trigger_lines(advances, ages, inst_cache, errors)
                lines = [
                    f"{candidate.entry_name()} = {{",
                    "\ttype = country",
                    "\ttext = {",
                    "\t\ttrigger = {",
                    *[f"\t\t\t{s}" for s in statements],
                    "\t\t}",
                    f"\t\tlocalization_key = {candidate.line_key()}",
                    "\t}",
                    "\ttext = {",
                    "\t\tlocalization_key = empty_text",
                    "\t}",
                    "}",
                ]
                entries.append("\n".join(lines))
    return HEADER.format(what="customizable localization entries") + "\n\n" + "\n\n".join(entries) + "\n"


def build_loc(sides_by_axis, by_token):
    lines = [HEADER.format(what="localization"), "l_english:"]
    for side in ("left", "right"):
        for token in sides_by_axis[side]:
            ordered = sort_side(by_token[token])
            body = "".join(f"[Player.Custom('{c.entry_name()}')]" for c in ordered)
            lines.append(f' GLORP_UI_SVH_BODY_{token.upper()}: "{body}"')
            for candidate in ordered:
                lines.append(f' {candidate.line_key()}: "{candidate.line_value()}"')
    return "\n".join(lines) + "\n"


def write_output(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(UTF8_BOM + text.encode("utf-8"))


def main():
    parser = argparse.ArgumentParser(
        description="Regenerate the GlorpUI takeable-only societal value hint files from the EU5 game files."
    )
    parser.add_argument(
        "-b",
        "--beta",
        action="store_true",
        help="Read from the closed beta install (Project Caesar Review).",
    )
    parser.add_argument(
        "--game-dir",
        help="EU5 game directory (overrides config.toml and auto-detection).",
    )
    args = parser.parse_args()

    game_root = _resolve_game_dir(args)
    print(f"Source: {game_root}")

    errors = []
    warnings = []

    ages = collect_ages(game_root, errors)
    axes, side_map = collect_axes(game_root, errors)
    constants = collect_constants(game_root)
    advances, reform_unlocks, law_unlocks, policy_unlocks = collect_advances(game_root, errors)
    loc_keys = collect_loc_keys(game_root)

    reforms, locked_reforms, reform_structural = collect_simple_candidates(
        game_root / "in_game" / "common" / "government_reforms", "r", constants, errors, warnings, ages
    )
    privileges, _, privilege_structural = collect_simple_candidates(
        game_root / "in_game" / "common" / "estate_privileges", "pv", constants, errors, warnings, ages
    )
    policies, locked_laws, law_structural = collect_policy_candidates(
        game_root / "in_game" / "common" / "laws", constants, errors, warnings
    )

    # Conditional modifier blocks can push the same side more than once (e.g. haijin_policy per IO
    # role); collapse to one line at the highest value.
    merged = {}
    for kind, key, law, token, value in reforms + privileges + policies:
        if token not in side_map:
            errors.append(f"unknown societal value side token on {key}: monthly_towards_{token}")
            continue
        pair = (kind, key, token)
        if pair in merged:
            warnings.append(
                f"multiple pushes for {key} toward {token}; keeping the highest value"
            )
            prev = merged[pair]
            merged[pair] = (kind, key, law, token, max(prev[4], value))
        else:
            merged[pair] = (kind, key, law, token, value)

    candidates = []
    for kind, key, law, token, value in merged.values():
        # A reach relaxation replaces that dimension's lock check, so it must not bypass a mechanic
        # lock; a dimension whose object carries a locked field stays strict.
        reach_map = {}
        if kind == "r":
            advs = reform_unlocks.get(key)
            if advs and key in locked_reforms:
                warnings.append(f"reform {key} is advance-unlocked but carries a locked field; keeping strict semantics")
                advs = None
            reach_map["self"] = advs
            structural = reform_structural.get(key, [])
        elif kind == "p":
            law_advs = law_unlocks.get(law)
            if law_advs and law in locked_laws:
                warnings.append(f"law {law} is advance-unlocked but carries a locked field; keeping strict semantics")
                law_advs = None
            reach_map["law"] = law_advs
            reach_map["self"] = policy_unlocks.get(key)
            structural = law_structural.get(law, [])
        else:
            structural = privilege_structural.get(key, [])
        candidates.append(Candidate(kind, key, law, token, value, reach_map, structural))

    # A swap must gain ground: hide a policy while the law's current policy pushes this side as
    # hard or harder.
    policy_groups = {}
    for candidate in candidates:
        if candidate.kind == "p":
            policy_groups.setdefault((candidate.law, candidate.token), []).append(candidate)
    for group in policy_groups.values():
        for candidate in group:
            for sibling in group:
                if sibling.key != candidate.key and sibling.value >= candidate.value:
                    candidate.structural.append(f"NOT = {{ has_policy = {sibling.key} }}")

    missing_names = sorted({c.key for c in candidates if c.key not in loc_keys})
    for key in missing_names:
        errors.append(f"no english loc key for candidate name: {key}")
    for token in sorted(side_map):
        if f"{token}_focus" not in loc_keys:
            errors.append(f"missing side label loc key: {token}_focus")

    for warning in warnings:
        print(f"WARNING: {warning}")
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        print("No files written.")
        return 1

    by_token = {}
    for candidate in candidates:
        by_token.setdefault(candidate.token, []).append(candidate)
    token_axis = {token: axis for token, (axis, _) in side_map.items()}
    sides_by_axis = {
        "left": [left for (_, left, _) in axes if left in by_token],
        "right": [right for (_, _, right) in axes if right in by_token],
    }

    inst_cache = {}
    outputs = [
        (GUI_OUTPUT, build_gui(sides_by_axis)),
        (
            SCRIPT_VALUES_OUTPUT,
            build_script_values(sides_by_axis, by_token, token_axis, advances, ages, inst_cache, errors),
        ),
        (CUSTOM_LOC_OUTPUT, build_custom_loc(sides_by_axis, by_token, advances, ages, inst_cache, errors)),
        (LOC_OUTPUT, build_loc(sides_by_axis, by_token)),
    ]
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        print("No files written.")
        return 1
    for path, text in outputs:
        write_output(path, text)

    for kind, label in (("pv", "privilege"), ("r", "reform"), ("p", "policy")):
        count = sum(1 for c in candidates if c.kind == kind)
        relaxed = sum(1 for c in candidates if c.kind == kind and any(c.reach_map.values()))
        print(f"{label} lines: {count} ({relaxed} advance-unlocked)")
    print(f"axis-sides with content: left {len(sides_by_axis['left'])}, right {len(sides_by_axis['right'])}")
    for path, _ in outputs:
        print(f"-> {path.relative_to(PROJECT_ROOT)}")

    return 0


def _load_config():
    """Return parsed config.toml as a dict, or empty dict if unavailable."""
    if tomllib is None:
        return {}
    try:
        with open(CONFIG_PATH, "rb") as f:
            return tomllib.load(f)
    except FileNotFoundError:
        return {}


def _resolve_game_dir(args):
    """Resolve the EU5 game root directory.

    Honors --game-dir, then config.toml (game_directory / beta_game_directory),
    then the known Steam install locations. Exits if no game directory is found.
    """
    if args.game_dir:
        game_dir = Path(args.game_dir)
        if game_dir.is_dir():
            return game_dir
        print(f"ERROR: Game directory not found: {game_dir}")
        sys.exit(1)

    cfg = _load_config()
    if args.beta:
        cfg_dir = cfg.get("beta_game_directory", "")
        search_paths = BETA_STEAM_GAME_PATHS
        config_key = "beta_game_directory"
        label = "EU5 closed beta"
    else:
        cfg_dir = cfg.get("game_directory", "")
        search_paths = STEAM_GAME_PATHS
        config_key = "game_directory"
        label = "EU5 game"

    if cfg_dir and Path(cfg_dir).is_dir():
        return Path(cfg_dir)

    for p in search_paths:
        if p.is_dir():
            return p

    print(f"ERROR: Could not locate {label} directory.")
    print(f"Set '{config_key}' in config.toml or use --game-dir.")
    sys.exit(1)


if __name__ == "__main__":
    sys.exit(main())
